name: rdcoletor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-323.2.beta

dependencies:
  csv: ^6.0.0
  flutter:
    sdk: flutter
  mobile_scanner: ^6.0.6
  path_provider: ^2.1.5
  sqflite: ^2.4.1

  path: any
  sqflite_common_ffi: ^2.3.6
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  file_picker: ^10.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
